title: CryptoNews
email: crypto@stefanovic.ventures
description: Learn about Bitcoin, other cryptocurrencies, blockchain technology, and more!
author: "Bojan Stefanovic"
url: "https://readcryptonews.com"
twitter_username: bojanstef
github_username:  bojanstef

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
